### ISSUE TITLE
Model size mismatch

### ISSUE THREAD

**Issue by kruthikakr** [Sreyan88/Indic-ASR#2]
Hi

I am trying to run the transcription.py  
 i have used your pretrained and fientuned model files from gdrive , but getting this error 

RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([318, 768]) from checkpoint, the shape in current model is torch.Size([314, 768]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([318]) from checkpoint, the shape in current model is torch.Size([314]).

any help please ?

**Comment by Sreyan88** [comment]
Hi @kruthikakr ,

Thank you for your interest in this repo. I would like to ask:

Which model are you using?
Are you using the same ltr file as required by the model?

**Comment by kruthikakr** [comment]
Here What is the /path/tomanifest file?

i am using all the files from multilingual-indic-ASR files 

import sys
sys.argv = ['']

import os



with open("/path/to/manifest", 'r') as file1:
    lines = file1.readlines()

files = []

for line in lines:
    feats = line.strip().split("\t")
    files.append(feats[0])

from stt_2 import Transcriber
transcriber = Transcriber(pretrain_model = '/path/to/pretrained/model/', finetune_model = '/path/to/finetuned/model/',
                          dictionary = '/path/to/dict.ltr.txt'',
                          lm_type = 'kenlm',
                          lm_lexicon = '/path/to/lexicon.txt', lm_model = '/path/to/lm.bin',
                          lm_weight = 1.5, word_score = -1, beam_size = 50)
hypos = transcriber.transcribe(files)

with open('output.txt', 'w') as f:
    for item in hypos:
        f.write("%s\n" % item)

**Comment by Sreyan88** [comment]
It should be the file that has all the paths to your inference files in a format:

```
path<tab>number-of-segments-in-audio-file
```

**Comment by kruthikakr** [comment]
yes , solved it
