### ISSUE TITLE
lexicon for code switching task (hindi-bengali)

### ISSUE THREAD

**Issue by BakingBrains** [Sreyan88/Indic-ASR#4]
Can you please provide lexicon.txt and lm.bin for hindi-bengali code switching.

I am able to run the procedure mentioned, but for code switching, the output file contains text in single language. I gave a audio input which consists of hindi and bengali. but the output is completetly in hindi.

Below is the output

```
लिबरऑफिस इम्प्रेस में एक प्रस्तुति डॉक्यूमेंट बनाना और बुनियादी फोर्माटिंग के इस स्पोकेन ट्यूटोरियल में आपका स्वागत है आ ऑनलाइन परीक्षा पास करे प्रशंसा पत्र दे विस्तारित तथ्य जन्य कॉन्टक्ट

```

Thanks

**Comment by Sreyan88** [comment]
Hi @BakingBrains ,

I just realized that I forgot to upload the "dict.ltr.txt" for the code-switched models. Can you please let me know what you are using?

**Comment by BakingBrains** [comment]
I am trying hindi_bengali code switching model. But the lexicon.txt and lm.bin is missing there. and the dict.Itr.txt which I used is here
[dict.ltr.txt](https://github.com/Sreyan88/Indic-ASR/files/7588121/dict.ltr.txt)

Thanks

**Comment by Sreyan88** [comment]
Hi there,

I have added new files (all that I could gather). Sorry for the delay.
