### ISSUE TITLE
Missing dic.ltr and lm files

### ISSUE THREAD

**Issue by kruthikakr** [Sreyan88/Indic-ASR#5]
Hi
In the drive link  for code switched folder  ---tonly_hindi folder : there is no dic , lexicon and lm files . And is this for Hindi_English code- switching inference ?

**Comment by Sreyan88** [comment]
Hi @kruthikakr ,

Looks like a mistake on my end. I am trying to get hold of the files as soon as possible. Thank You for your patience.

**Comment by kruthikakr** [comment]
@Sreyan88  thank you for your response

**Comment by Sreyan88** [comment]
Hi there,

I have added new files (all that I could gather). Sorry for the delay.
