### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by rishabbjain** [Sreyan88/Indic-ASR#7]
hi, what is the path to manifest in the inference file?

**Comment by Sreyan88** [comment]
manifest file should be your file with path to wav files you want to infer on

**Comment by rishabbjain** [comment]
is it okay, if i provide just one local wav file path?

**Comment by Sreyan88** [comment]
ye sure, please take care the original fine is tab-separated, so just take care of that in transcription.py

**Comment by rishabbjain** [comment]
ran the transcription.py with a 4 sec wav file and with all the files in
the multilingual folder. but getting this error. can you help?

**Comment by Sreyan88** [comment]
which error exactly?

**Comment by rishabbjain** [comment]
Runtime error: error in loading state_dict for wav2vecCtc
Size mismatch for w2v_encoder.proj.weight and bias

**Comment by Sreyan88** [comment]
I hope the problem is solved. Thank You for your interest in the repo :)
